apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  type: ClusterIP
  selector:
    app: blue
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  type: ClusterIP
  selector:
    app: red
  ports:
  - port: 80
    targetPort: 8080