apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
    app: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: kodekloud/webapp-color
        env:
        - name: APP_COLOR
          value: blue
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deploy
  labels:
    app: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red
        image: kodekloud/webapp-color
        env:
        - name: APP_COLOR
          value: red
        ports:
        - containerPort: 8080
