apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: default
  labels:
    app: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: simple-web
        image: omoknooni/simple-web:latest
        ports:
        - containerPort: 5000