apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: default
  labels:
    app: simple_web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple_web
  template:
    metadata:
      labels:
        app: simple_web
    spec:
      containers:
      - name: simple_web
        image: omoknooni/simple_web:latest
        ports:
        - containerPort: 5000